manager_node:
  ros__parameters:
    uneven_map/iter_num: 2
    uneven_map/map_size_x: 10.0
    uneven_map/map_size_y: 10.0
    uneven_map/ellipsoid_x: 0.2
    uneven_map/ellipsoid_y: 0.1
    uneven_map/ellipsoid_z: 0.1
    uneven_map/xy_resolution: 0.05
    uneven_map/yaw_resolution: 0.1
    uneven_map/min_cnormal: 0.8
    uneven_map/max_rho: 0.05
    uneven_map/gravity: 9.81
    uneven_map/mass: 1.0
    uneven_map/map_pcd: "install/uneven_map/share/uneven_map/maps/desert.pcd"
    uneven_map/map_file: "install/uneven_map/share/uneven_map/maps/desert.map"

    kino_astar/yaw_resolution: 3.15
    kino_astar/lambda_heu: 1.0
    kino_astar/weight_r2: 1.0
    kino_astar/weight_so2: 0.5
    kino_astar/weight_v_change: 0.0
    kino_astar/weight_delta_change: 0.0
    kino_astar/weight_sigma: 10.0
    kino_astar/time_interval: 0.3
    kino_astar/collision_interval: 0.06
    kino_astar/oneshot_range: 1.0
    kino_astar/wheel_base: 0.26
    kino_astar/max_steer: 0.5
    kino_astar/max_vel: 0.5
    kino_astar/in_test: false

    alm_traj_opt/rho_T: 100000.0
    alm_traj_opt/rho_ter: 10.0
    alm_traj_opt/max_vel: 0.5
    alm_traj_opt/max_acc_lon: 5.0
    alm_traj_opt/max_acc_lat: 10.0
    alm_traj_opt/max_kap: 2.1
    alm_traj_opt/min_cxi: 0.8
    alm_traj_opt/max_sig: 0.05
    alm_traj_opt/use_scaling: true
    alm_traj_opt/rho: 1.0
    alm_traj_opt/beta: 1000.0
    alm_traj_opt/gamma: 1.0
    alm_traj_opt/epsilon_con: 0.001
    alm_traj_opt/max_iter: 10.0
    alm_traj_opt/g_epsilon: 1.0e-03
    alm_traj_opt/min_step: 1.0e-32
    alm_traj_opt/inner_max_iter: 10000.0
    alm_traj_opt/delta: 1.0e-4
    alm_traj_opt/mem_size: 256
    alm_traj_opt/past: 3
    alm_traj_opt/int_K: 16
    alm_traj_opt/in_test: false
    alm_traj_opt/in_debug: false

    manager/piece_len: 0.3
    manager/mean_vel: 0.5
    manager/init_time_times: 1.2
    manager/yaw_piece_times: 2.0
    manager/init_sig_vel: 0.05
    manager/bk_dir: "xxx"

mpc:
  ros__parameters:
    du_threshold: 0.001
    dt: 0.02
    max_iter: 150
    predict_steps: 30
    delay_num: 0
    max_omega: 24.0
    max_domega: 10.0
    max_speed: 0.8
    min_speed: -0.8
    max_accel: 10.0
    test_mpc: false
    bk_mode: false
    matrix_q: [100.0, 100.0, 2.0]
    matrix_r: [0.01, 0.01]
    matrix_rd: [0.01, 100.0]
    max_steer: 0.505
    max_dsteer: 1.5
    wheel_base: 0.26
    model_type: 2